version: '3.9'
services:
  nestapp:
    container_name: nestapp
    image: francescoxx/nestapp:1.0.0
    build: .
    ports:
      - '4000:4000'
    environment:
      - DB_TYPE=postgres
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_DB=postgres
      - PG_PORT=5432
      - PG_HOST=db
      - JWT_SECRET=thisisasecret
      - JWT_EXPIRES=3600m
      - DB_ENTITIES=src/*/entities/*.entity.ts
      - DB_SYNCRONIZE=true
      - DB_LOGGING=true
      - DB_MIGRATIONS_RUN=true
      - DB_MIGRATIONS_DIR=migrations
      - SALT_ROUNDS=10
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:12
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}